[tool.poetry]
name = "learning-postgresql"
version = "0.1.0"
description = ""
authors = ["Fredrik Averpil <fredrik.averpil@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.2"
pytest-randomly = "^3.11.0"
psycopg2-binary = "^2.9.3"
peewee = "^3.14.10"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
flake8-bugbear = "^22.4.25"
flake8-bandit = "^3.0.0"
flake8-builtins = "^1.5.3"
flake8-pytest-style = "^1.6.0"
flake8-isort = "^4.1.1"
mypy = "^0.950"

[tool.pytest.ini_options]
testpaths = "tests"

[tool.isort]
profile = "black"
line_length = "120"

[[tool.mypy.overrides]]
module = [
    "playhouse.*",
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
