name: check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: cpython_setup
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ matrix.os }}-py-${{ steps.cpython_setup.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - run: pipx install poetry --python '${{ steps.cpython_setup.outputs.python-path }}'
      - run: poetry install
      - run: poetry run ruff .
      - run: poetry run black --check --diff tests

  type:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: cpython_setup
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ matrix.os }}-py-${{ steps.cpython_setup.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - run: pipx install poetry --python '${{ steps.cpython_setup.outputs.python-path }}'
      - run: poetry install
      - run: poetry run mypy tests
