name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up postgres --detach
      # temporary; sleep until db comes around
      - run: /usr/bin/bash -c "sleep 10"
      - uses: actions/setup-python@v4
        id: cpython_setup
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ matrix.os }}-py-${{ steps.cpython_setup.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - run: pipx install poetry --python '${{ steps.cpython_setup.outputs.python-path }}'
      - run: poetry install --no-dev
      - run: poetry run pytest -vv -rxXs
      - run: docker compose down --volumes --remove-orphans
